### ISSUE TITLE
Improve Integration with pymc-examples

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/pymc-bart#14]
#7 is a hacky way to render the notebooks hosted in pymc-examples here.
We need to find a better way

**Comment by ketyi** [comment]
Where could I find a BART OOS prediction example with latest pymc 5 and pymc_bart?

**Comment by aloctavodia** [comment]
We need to add an example, You can do the same as with other PyMC models. 



```python
    with pm.Model() as model:
        data_X = pm.MutableData("data_X", X)
        mu = pmb.BART("mu", data_X, Y)
        ...
        ...
        idata = pm.sample()

    with model:
        pm.set_data({"data_X": another_X})
        ppc = pm.sample_posterior_predictive(idata)
```

**Comment by ketyi** [comment]
Maybe my expectation is wrong but there is something weird in the posterior-predictive-check object. I've made a small example to show you:
https://colab.research.google.com/drive/1w8aFUHAk3oJ60PEKZKuBlk9dMt8kRnK_?usp=sharing
Isn't it supposed to be a 5-length series? It somehow keeps the "old" data_X dimensionality (of 10) and its content is not so valid either...

![image](https://user-images.githubusercontent.com/14096902/210215383-b09b867d-27b0-43b6-9d64-918ce6745e3b.png)

**Comment by aloctavodia** [comment]
Sorry, I have updated the example. You also need to specify the shape of the observed variable to be that of the Bart variable.

**Comment by ketyi** [comment]
> Sorry, I have updated the example. You also need to specify the shape of the observed variable to be that of the Bart variable.

Thank you, @aloctavodia . Technically it's working now but it doesn't forecast as expected (it's supposed to model a simple linear trend). I've updated my colab notebook as well. What am I doing wrong?

![image](https://user-images.githubusercontent.com/14096902/210247404-42e1bd94-f7ab-4307-b27f-608c878ef260.png)

**Comment by aloctavodia** [comment]
That's the expected behavior for extrapolation, BART is just partitioning the data into hyperrectangles based on the observed data. Anything outside is going to be assigned constant values that are going to to approximately equal to those at the boundaries, in your example 0 to the left and 9 to the right.

This is a common feature of BART, not just pymc_bart. There has been some proposal to improve extrapolation of BART models like making the node values return a linear regression or even a GP, instead of scalars.

**Comment by ketyi** [comment]
Understood, many thanks for the elaboration.

**Comment by aloctavodia** [comment]
Thanks for the feedback, I will use it to update the documentation.
