### ISSUE TITLE
Issue with import error can't find _moment in pymc

### ISSUE THREAD

**Issue by Nilavro** [pymc-devs/pymc-bart#153]
I am getting an import error. My pymc version is 5.11.0. 

Looks like the code is from this line https://github.com/pymc-devs/pymc-bart/blob/02bb1106cbdb5d61cf6d3c1ccb1695771b8390eb/pymc_bart/bart.py#L25

and I don't see _moment in pymc https://github.com/pymc-devs/pymc/blob/main/pymc/distributions/distribution.py

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File <command-4197283569386904>:1
----> 1 import pymc_bart as pmb

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you’re seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-c236e0d8-44f4-44c5-ab19-c16f95173335/lib/python3.9/site-packages/pymc_bart/__init__.py:16
      1 #   Copyright 2022 The PyMC Developers
      2 #
      3 #   Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 #   See the License for the specific language governing permissions and
     13 #   limitations under the License.
     14 import pymc as pm
---> 16 from pymc_bart.bart import BART
     17 from pymc_bart.pgbart import PGBART
     18 from pymc_bart.split_rules import ContinuousSplitRule, OneHotSplitRule, SubsetSplitRule

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you’re seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-c236e0d8-44f4-44c5-ab19-c16f95173335/lib/python3.9/site-packages/pymc_bart/bart.py:25
     23 import pytensor.tensor as pt
     24 from pandas import DataFrame, Series
---> 25 from pymc.distributions.distribution import Distribution, _moment
     26 from pymc.logprob.abstract import _logprob
     27 from pytensor.tensor.random.op import RandomVariable

ImportError: cannot import name '_moment' from 'pymc.distributions.distribution' (/local_disk0/.ephemeral_nfs/envs/pythonEnv-c236e0d8-44f4-44c5-ab19-c16f95173335/lib/python3.9/site-packages/pymc/distributions/distribution.py)`

**Comment by aloctavodia** [comment]
Thanks for taking the time to report this, See #152. This is being addressed in the meantime you can use an older version of PyMC.

**Comment by aloctavodia** [comment]
Fixed in the latest release
