### ISSUE TITLE
Pyensor >= 2.26.0 support?

### ISSUE THREAD

**Issue by danieltomasz** [pymc-devs/pymc-bart#204]
Currently this library is pinned to pymc-5.18.0  and pytensor-2.25.5. Is there any reason that there is no support for pytensor 2.26? Pytensor 2.26 fixes problem with Apple Accelerate framework on MacOS Sequoia, which make the computations faster, would be beneficial for users that they can use this version with better support for numerical computations.

EDIT: Apart of the fact that the latest pymc-bart release is on 2024-11-7 and pytensor was released on 2024-11-8.

**Comment by aloctavodia** [comment]
We pinned the pymc version to ensure changes in pymc doesn't break pymc-bart. We should check and do a new release.

**Comment by danieltomasz** [comment]
Yes, this is best practice, I just letting know here that could be useful to consider to update dependencies for the aforementioned reason.
