### ISSUE TITLE
Question: BART with Binomial liikelihood?

### ISSUE THREAD

**Issue by juanitorduz** [pymc-devs/pymc-bart#31]
Hi! 👋 ! I am trying to use a BART to model a Binomial likelihood as

```python
with pm.Model() as model:
    mu = pmb.BART(name="mu", X=x, Y=k)
    p = pm.Deterministic(name="p", var=pm.math.invlogit(mu))
    pm.Binomial(name="likelihood", n=n, p=p, observed=k)
```
However I have problems sampling as the initial value of `mu` is very high and makes `p=1.0`. I tried changing the `initval` but Ii believe the problem is conceptual: According to https://bayesiancomputationbook.com/markdown/chp_07.html#the-bart-model The BART model works when modeling the expected value. For the normal, poisson, negative-binomial and Bernoulli this is fine as one of the parameters represents the mean. This is however not the case for a Binomial distribution `Binomial(n, p)` where the expected value is `np`. Do you have a tip or trick to use BART with a Binomial likelihood? Or am I missing something ini the model parametrization ? 

**Remark** It seems the `inv_link` from BART is not available in `pymc 5.0.1` right? 

Thanks :)

**Comment by aloctavodia** [comment]
Hi, 

I think this can be solved by subtracting a small number to `pm.math.invlogit(mu)` or something fancier, like [what we do in Bambi](https://github.com/bambinos/bambi/blob/99e30268bb15748acdf776a478c75067590e1b2d/bambi/backend/links.py).

The original BART model and many of its variations and implementations model the expected value, and thus it is generally discussed in those terms. But the pymc_bart implementation is more flexible, and hence probably a better way to describe it is as a prior over step functions. With the support of such a function being the real line. This is true starting with PyMC 4, so we deprecated `inv_link`.

The goal of PyMC_BART is that it should work with any likelihood the user picks and any of its parameters. It should not be a problem to model `p` of the Binomial or `sigma` from a Normal... In practice, I think I have only tried with Normal, Student, Poisson, NegativeBinomial, Binomial, and Asymmetric Laplace.

**Comment by juanitorduz** [comment]
Thanks you for the input! Much appreciated!  I will try it out.
If you want you can close this issue ... or even better we could add the second paragraph ("The original BART model  ...") to the docs :). I think is a very useful remark.

**Comment by juanitorduz** [comment]
btw! it worked! I'll share the results once I clean them up! :)

**Comment by aloctavodia** [comment]
Great news. And thanks for asking and sharing. As we are still unsure of the practical limits and strengths of BART example, both when it works and when it doesn't, are much appreciated.

**Comment by juanitorduz** [comment]
[Here](https://github.com/juanitorduz/website_projects/blob/master/Python/retention_bart.ipynb) you can find a first iteration of the simulated example: BART model with Binomial likelihood.
