### ISSUE TITLE
Should PG-BART re-sample particles without copying them?

### ISSUE THREAD

**Issue by elanmart** [pymc-devs/pymc-bart#4]
Hi!

I was looking at @aloctavodia 's implementation of PG-BART, and I noticed that when particles are re-sampled, it's done with replacement, but without copy [here]( https://github.com/pymc-devs/pymc-experimental/blob/main/pymc_experimental/bart/pgbart.py#L178):
```python
particles[2:] = particles[new_indices]
```

Is this intended? These particles are then modified in-place (e.g., by popping from the list of expansion nodes).
So, if `new_indices` is for example `[0, 1, 2, 0]`, then modyfing the first particle [here](https://github.com/pymc-devs/pymc-experimental/blob/main/pymc_experimental/bart/pgbart.py#L152-L163) will also modify the last one.

Should it perhaps be instead written as:
```python
particles[2:] = [deepcopy(particles[i]) for i in new_indices]
```
?

**Comment by aloctavodia** [comment]
Hi @elanmart you are right, thanks for reporting this issue. I will submit an issue fixing this, with a slight variation of your proposal in order to reduce computational time.

Notice that I have transferred this issue, this is the new repository where BART is going to be developed.
