### ISSUE TITLE
Add example using shared variables

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/pymc-bart#48]
Currently, the only "example" is a test :-(

https://github.com/pymc-devs/pymc-bart/blob/main/tests/test_bart.py#L43-L58

**Comment by juanitorduz** [comment]
I think I could help with this one as I have been working with BART for out-of-sample predictions lately. I was thinking about using the `bikes` example. Should it be a different notebook or an extension of the existing one? https://github.com/pymc-devs/pymc-examples/blob/main/examples/case_studies/BART_introduction.ipynb

**Comment by aloctavodia** [comment]
Thanks! Both options are good.

**Comment by juanitorduz** [comment]
Here is my first proposal: https://github.com/pymc-devs/pymc-examples/pull/507
