### ISSUE TITLE
Improve integration with pymc-examples

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/pymc-bart#49]
https://github.com/pymc-devs/pymc-bart/pull/7 is a hacky way to render the notebooks hosted in pymc-examples here.
We need to find a better way. 

@OriolAbril do you have a suggestion?

**Comment by OriolAbril** [comment]
is it necessary to render them there? or is it enough to have a link on the sidebar/navbar pointing to the right notebook in pymc-examples?

**Comment by aloctavodia** [comment]
I was hoping to have the notebook rendered on both sites. But maybe a link is enough.
