### ISSUE TITLE
implement fast PDP computation

### ISSUE THREAD

**Issue by aloctavodia** [pymc-devs/pymc-bart#69]
The way we compute the partial dependence plot is very demanding. We can reduce computational cost as explained here https://nicolas-hug.com/blog/pdps

**Comment by PabloGGaray** [comment]
Maybe we could keep both methods, using the Fast Method as default and the option to use the Slow Method. Considering that the second one could take into account possible values not seen yet.

**Comment by aloctavodia** [comment]
Maybe keep the fast method as the default for plot_depedence and then add a new function or option to allow the user to easily explore counterfactuals
