### ISSUE TITLE
mypy  support

### ISSUE THREAD

**Issue by juanitorduz** [pymc-devs/pymc-bart#76]
When trying to work on https://github.com/pymc-devs/pymc-bart/pull/74 I felt type hints would have been very helpful. Also, they can help with developing and testing. As this code base is relatively small I think it would be nice to add type hints and add mypy checks in the tests. I would be happy to kick this off is you agree it is useful.

**Comment by aloctavodia** [comment]
Thanks for offering help. Yes, I think this could be a good addition.

**Comment by juanitorduz** [comment]
shall we close this one now :) ?
