### ISSUE TITLE
Update intro notebook ... predict method missing `m` argument

### ISSUE THREAD

**Issue by juanitorduz** [pymc-devs/pymc-bart#87]
I am trying to run the intro notebook https://www.pymc.io/projects/examples/en/latest/case_studies/BART_introduction.html from the `main` branch. I am getting an error when running:

```python
bart_trees = μ_.owner.op.all_trees
for i in [0, 1, 2]:
    plt.step(x_data[:, 0], [bart_trees[0][i].predict(x) for x in x_data])
```

yields

```python
TypeError                                 Traceback (most recent call last)
Cell In[50], line 3
      1 bart_trees = μ_.owner.op.all_trees
      2 for i in [0, 1, 2]:
----> 3     plt.step(x_data[:, 0], [bart_trees[0][i].predict(x) for x in x_data])

Cell In[50], line 3, in (.0)
      1 bart_trees = μ_.owner.op.all_trees
      2 for i in [0, 1, 2]:
----> 3     plt.step(x_data[:, 0], [bart_trees[0][i].predict(x) for x in x_data])

TypeError: Tree.predict() missing 1 required positional argument: 'm'
```

Shall we fix the example, or is there anything to re-think regarding the `predict` method arguments?

**Comment by aloctavodia** [comment]
I think we should fix the example.

Predict is not intended to be directly accesed by users. Do you think is can be confusing to show it in the intro notebook? In that case we can remove it. Or be sure that readers understand the purpose of the example is just pedagogical.

**Comment by juanitorduz** [comment]
We can fix it and warn the user this method should be *private*. It illustrates a nice point.

**Comment by aloctavodia** [comment]
Agreed

**Comment by aloctavodia** [comment]
on second thought I am removing `m` from predict.

**Comment by PabloGGaray** [comment]
Could we close this issue?
