### ISSUE TITLE
New beta parameter missing in doc-string

### ISSUE THREAD

**Issue by juanitorduz** [pymc-devs/pymc-bart#93]
In https://github.com/pymc-devs/pymc-bart/pull/91 a new parameter `beta` was added to the `BART` constructor but Is missing on the doc-string. It would be nice to have a description of the meaning of this parameter and maybe tips regarding the best range of values to be used. See https://github.com/pymc-devs/pymc-bart/blob/main/pymc_bart/bart.py#L67-#L104

**Comment by aloctavodia** [comment]
good catch. alpha and beta have the same meaning as in the original BART paper https://projecteuclid.org/journals/annals-of-applied-statistics/volume-4/issue-1/BART-Bayesian-additive-regression-trees/10.1214/09-AOAS285.full

**Comment by juanitorduz** [comment]
Actually we should also update the description of `alpha` as it says it should be ideally in `(0, 0.5)` and the new default is $0.95$ ;)
