### ISSUE TITLE
Specify a negative binomial model using BART structure

### ISSUE THREAD

**Issue by gzhai001** [pymc-devs/pymc-bart#97]
Hello All,

I specify a commonly used negative binomial model with pymc_bart as the tutorials (https://www.pymc.io/projects/examples/en/latest/case_studies/BART_introduction.html): 

with pm.Model() as model_bikes:
    α = pm.Exponential("α", 1)
    μ = pmb.BART("μ", X, np.log(Y), m=50)
    y = pm.NegativeBinomial("y", mu=pm.math.exp(μ), alpha=α, observed=Y)
    idata_bikes = pm.sample(compute_convergence_checks=False, random_seed=RANDOM_SEED)

However, if some Y values equal zero, the model specification will generate sampling errors.

**Comment by aloctavodia** [comment]
Did you still get errors if you did something like μ = pmb.BART("μ", X, np.log(Y+epsilon), m=50)

Where epsilon is a very small value

**Comment by gzhai001** [comment]
It works when adding a positive epsilon. In my view, μ = log(lambda) = BART (x); y ~ NB(lambda = exp(mu), alpha).

Of course,  we could add a small positive epsilon to Y. However, the pmb.BART does not fit the log(lambda) as the traditional statistical negative binomial model does.

**Comment by aloctavodia** [comment]
Glad it helped. Just to clarify, the Y value passed to pmb.BART it is used to get an initial value for the sum of trees and variance of the leaf nodes.
